In [1]:
import torch

In [3]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [4]:
x[1, 0:2, 0:3] # second block, both rows, all three columns

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [5]:
# similar
x[1, :, :] # second block, both rows, all three columns

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])