In [3]:
# !pip3 install torch

In [23]:
import torch
import numpy as np

In [8]:
v = torch.tensor([1,2,3])
print(v[2])

tensor(3)


In [9]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:4])

tensor([2, 3, 4])


In [11]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [16]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)
print(f.dtype)
print(f.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [19]:
v.view(6,1) # similar to reshape in numpy, the compatibility constraints are the same for transformation

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [20]:
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [22]:
v.view(3, -1) # -1 allows it to infer the columns as per the tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [27]:
a = np.array([1,2,3,4,5,6])
# to convert to torch tensor from numpy
tensorcnv = torch.from_numpy(a)
print(tensorcnv)
print(tensorcnv.type())

tensor([1, 2, 3, 4, 5, 6])
torch.LongTensor


In [28]:
# convert it back to numpy arrays
numpycnv = tensorcnv.numpy()
print(numpycnv)

[1 2 3 4 5 6]
