In [1]:
import torch

In [2]:
one_d = torch.arange(0, 10, 2)
print(one_d)

tensor([0, 2, 4, 6, 8])


In [3]:
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
# for checking the dimensions
two_d.dim()

2

In [9]:
two_d[0]

tensor([0, 1, 2])

In [10]:
two_d[0][0]

tensor(0)

In [12]:
two_d[1][2]

tensor(5)

In [15]:
x = torch.arange(18).view(2,3,3) # two sheets 3 rows 3 columns
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [16]:
x = torch.arange(18).view(3,3,2) # 3 sheets 3 rows 2 columns
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [17]:
x = torch.arange(36).view(3,3,4) # 3 sheets 3 rows 2 columns
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])