# Convolutions

In [20]:
import torch
from torch import nn

## 1D Convolutions

In [13]:
conv = nn.Conv1d(2, 16, 3) # 2 channels (assume stereo signal), 16 kernels of size 3
conv

Conv1d(2, 16, kernel_size=(3,), stride=(1,))

In [16]:
conv.weight.size() 

torch.Size([16, 2, 3])

In [17]:
conv.bias.size()

torch.Size([16])

In [38]:
x = torch.randn(1, 2, 64)
x

tensor([[[ 0.2541, -0.8274, -0.9374, -0.6766, -0.3347,  0.3397, -0.2336,
           0.5670,  0.0135,  1.0712,  0.4403,  0.2211, -0.1915, -1.6519,
          -0.6750, -1.5473,  1.0150, -0.2492,  0.4649,  1.8273,  0.7328,
          -0.2198,  0.4638, -0.1005,  1.3831,  0.6270,  1.8321, -0.2153,
          -0.2832,  1.5699,  1.9084,  2.4466, -0.1779, -0.2487,  0.1157,
          -0.8031, -1.7095,  1.4021,  0.3244,  0.5331, -1.6516, -0.1977,
          -0.3379,  1.3615, -0.2133,  0.8629, -0.7841, -0.5295,  3.1171,
           1.2273, -0.2677, -0.0868,  0.8791,  1.0471,  0.1599, -1.0634,
           0.9788, -0.6566,  0.5963, -0.1734, -0.0843,  0.9240,  0.8134,
          -0.2428],
         [ 2.6026, -0.1103,  0.7450, -1.3704,  0.0442,  0.9253, -1.7648,
          -0.4773,  0.1544,  0.5947,  0.5285, -0.4236,  1.2030,  0.2146,
          -0.9988, -1.0654, -0.0957,  0.9927, -0.5874, -1.3259, -1.2192,
          -0.3401,  0.4114, -0.3785,  1.2367, -0.8944,  0.7113, -1.2171,
           1.2202,  0.1945,  1.

In [39]:
conv(x).size()

torch.Size([1, 16, 62])

In [40]:
conv = nn.Conv1d(2, 16, 5)

In [41]:
conv(x).size()

torch.Size([1, 16, 60])

## 2D Convolutions

In [44]:
x = torch.rand(1, 20, 64, 128) # 1 sample, 20 channels, height 64, and width
x.shape

torch.Size([1, 20, 64, 128])

In [45]:
conv = nn.Conv2d(20, 16, (3, 5)) # 20 channels, 16 kernels, kernel size is 3 x 5
conv

Conv2d(20, 16, kernel_size=(3, 5), stride=(1, 1))

In [46]:
conv.weight.size()

torch.Size([16, 20, 3, 5])

In [47]:
conv(x).size()

torch.Size([1, 16, 62, 124])

In [48]:
# 20 channels, 16 kernels of size 3 x 5, stride is 1 , padding of 1 and 2
conv = nn.Conv2d(20, 16, (3, 5), 1, (1, 2))
conv

Conv2d(20, 16, kernel_size=(3, 5), stride=(1, 1), padding=(1, 2))

In [49]:
conv(x).size()

torch.Size([1, 16, 64, 128])

## How automatic gradient works?

In [57]:
n = 6
x = torch.arange(1., n + 1, requires_grad = True)
x

tensor([1., 2., 3., 4., 5., 6.], requires_grad=True)

In [58]:
w = torch.ones(n, requires_grad = True)
w

tensor([1., 1., 1., 1., 1., 1.], requires_grad=True)

In [59]:
z = w @ x
z

tensor(21., grad_fn=<DotBackward>)

In [60]:
z.backward()

In [61]:
print(x.grad, w.grad, sep = '\n')

tensor([1., 1., 1., 1., 1., 1.])
tensor([1., 2., 3., 4., 5., 6.])


In [63]:
# having with torch.no_grad() omits gradient accumulation
x = torch.arange(1., n + 1)
w = torch.ones(n, requires_grad = True)
x, w

(tensor([1., 2., 3., 4., 5., 6.]),
 tensor([1., 1., 1., 1., 1., 1.], requires_grad=True))

In [64]:
# all torch tensors will not have gradient accumulation
with torch.no_grad():
    z = w @ x 

try:
    z.backward() # error, because z has no grad

except RuntimeError as e:
    print('RuntimeError!!!')
    print(e)

RuntimeError!!!
element 0 of tensors does not require grad and does not have a grad_fn
